source 'http://rubygems.org'
gem 'rails', '3.2.12'
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end
gem 'jquery-rails'
gem 'thin', '>= 1.5.0'
gem 'mysql2', '>= 0.3.11'
gem 'bootstrap-sass', '>= 2.3.0.0'
gem 'devise', '>= 2.2.3'
gem 'cancan', '>= 1.6.8'
gem 'rolify', '>= 3.2.0'
gem 'simple_form', '>= 2.0.4', '< 2.1.0'
gem 'client_side_validations'
gem 'client_side_validations-simple_form'
gem 'figaro', '>= 0.5.3'
gem 'better_errors', '>= 0.6.0', :group => :development
gem 'binding_of_caller', '>= 0.7.1', :group => :development, :platforms => [:mri_19, :rbx]
gem 'will_paginate', '~> 3.0'
gem 'bootstrap-will_paginate'
gem 'ransack'
gem 'simple_calendar', '~> 0.1.5'
gem 'prawn'
gem 'prawn_rails'
gem 'acts_as_list'